#!/usr/bin/env bash

# source venv3/bin/activate
# cd /l/vision/v5/yiju/glomeruli_detection/
# PATH=/l/vision/v5/yiju/openslide/bin:$PATH
# export PATH
# LD_LIBRARY_PATH=/l/vision/v5/yiju/openslide/lib:$LD_LIBRARY_PATH
# export LD_LIBRARY_PATH


python detect_glomus_test.py     --target_list=VU_test_data/05/02_PAS/opt_pas_test_list.txt     --data_dir=VU_test_data/05/     --staining=OPT_PAS     --output_dir=/l/vision/v5/yiju/glomeruli_detection/VU_test_data/05/output    --output_file_ext=PNG     --model=model/pas_train1/     --window_size=1000     --overlap_ratio=0.5     --conf_threshold=0.2
python detect_glomus_test.py     --target_list=VU_test_data/06/02_PAS/opt_pas_test_list.txt     --data_dir=VU_test_data/06/     --staining=OPT_PAS     --output_dir=/l/vision/v5/yiju/glomeruli_detection/VU_test_data/06/output    --output_file_ext=PNG     --model=model/pas_train1/     --window_size=1000     --overlap_ratio=0.5     --conf_threshold=0.2
python detect_glomus_test.py     --target_list=VU_test_data/07/02_PAS/opt_pas_test_list.txt     --data_dir=VU_test_data/07/     --staining=OPT_PAS     --output_dir=/l/vision/v5/yiju/glomeruli_detection/VU_test_data/07/output    --output_file_ext=PNG     --model=model/pas_train1/     --window_size=1000     --overlap_ratio=0.5     --conf_threshold=0.2
python detect_glomus_test.py     --target_list=VU_test_data/08/02_PAS/opt_pas_test_list.txt     --data_dir=VU_test_data/08/     --staining=OPT_PAS     --output_dir=/l/vision/v5/yiju/glomeruli_detection/VU_test_data/08/output    --output_file_ext=PNG     --model=model/pas_train1/     --window_size=1000     --overlap_ratio=0.5     --conf_threshold=0.2
python detect_glomus_test.py     --target_list=VU_test_data/09/02_PAS/opt_pas_test_list.txt     --data_dir=VU_test_data/09/     --staining=OPT_PAS     --output_dir=/l/vision/v5/yiju/glomeruli_detection/VU_test_data/09/output    --output_file_ext=PNG     --model=model/pas_train1/     --window_size=1000     --overlap_ratio=0.5     --conf_threshold=0.2
python detect_glomus_test.py     --target_list=VU_test_data/10/02_PAS/opt_pas_test_list.txt     --data_dir=VU_test_data/10/     --staining=OPT_PAS     --output_dir=/l/vision/v5/yiju/glomeruli_detection/VU_test_data/10/output    --output_file_ext=PNG     --model=model/pas_train1/     --window_size=1000     --overlap_ratio=0.5     --conf_threshold=0.2
python detect_glomus_test.py     --target_list=VU_test_data/12/02_PAS/opt_pas_test_list.txt     --data_dir=VU_test_data/12/     --staining=OPT_PAS     --output_dir=/l/vision/v5/yiju/glomeruli_detection/VU_test_data/12/output    --output_file_ext=PNG     --model=model/pas_train1/     --window_size=1000     --overlap_ratio=0.5     --conf_threshold=0.2
python detect_glomus_test.py     --target_list=VU_test_data/13/02_PAS/opt_pas_test_list.txt     --data_dir=VU_test_data/13/     --staining=OPT_PAS     --output_dir=/l/vision/v5/yiju/glomeruli_detection/VU_test_data/13/output    --output_file_ext=PNG     --model=model/pas_train1/     --window_size=1000     --overlap_ratio=0.5     --conf_threshold=0.2
python detect_glomus_test.py     --target_list=VU_test_data/14/02_PAS/opt_pas_test_list.txt     --data_dir=VU_test_data/14/     --staining=OPT_PAS     --output_dir=/l/vision/v5/yiju/glomeruli_detection/VU_test_data/14/output    --output_file_ext=PNG     --model=model/pas_train1/     --window_size=1000     --overlap_ratio=0.5     --conf_threshold=0.2
python detect_glomus_test.py     --target_list=VU_test_data/16/02_PAS/opt_pas_test_list.txt     --data_dir=VU_test_data/16/     --staining=OPT_PAS     --output_dir=/l/vision/v5/yiju/glomeruli_detection/VU_test_data/16/output    --output_file_ext=PNG     --model=model/pas_train1/     --window_size=1000     --overlap_ratio=0.5     --conf_threshold=0.2
python detect_glomus_test.py     --target_list=VU_test_data/52/02_PAS/opt_pas_test_list.txt     --data_dir=VU_test_data/52/     --staining=OPT_PAS     --output_dir=/l/vision/v5/yiju/glomeruli_detection/VU_test_data/52/output    --output_file_ext=PNG     --model=model/pas_train1/     --window_size=1000     --overlap_ratio=0.5     --conf_threshold=0.2

python merge_overlapped_glomus.py     --target_list=VU_test_data/05/02_PAS/opt_pas_test_list.txt     --detected_list=VU_test_data/05/output/OPT_PASPNG.csv     --data_dir=VU_test_data/05/     --staining=OPT_PAS     --output_dir=/l/vision/v5/yiju/glomeruli_detection/VU_test_data/05/output     --output_file_ext=PNG     --conf_threshold=0.9     --overlap_threshold=0.35
python merge_overlapped_glomus.py     --target_list=VU_test_data/06/02_PAS/opt_pas_test_list.txt     --detected_list=VU_test_data/06/output/OPT_PASPNG.csv     --data_dir=VU_test_data/06/     --staining=OPT_PAS     --output_dir=/l/vision/v5/yiju/glomeruli_detection/VU_test_data/06/output     --output_file_ext=PNG     --conf_threshold=0.9     --overlap_threshold=0.35
python merge_overlapped_glomus.py     --target_list=VU_test_data/07/02_PAS/opt_pas_test_list.txt     --detected_list=VU_test_data/07/output/OPT_PASPNG.csv     --data_dir=VU_test_data/07/     --staining=OPT_PAS     --output_dir=/l/vision/v5/yiju/glomeruli_detection/VU_test_data/07/output     --output_file_ext=PNG     --conf_threshold=0.9     --overlap_threshold=0.35
python merge_overlapped_glomus.py     --target_list=VU_test_data/08/02_PAS/opt_pas_test_list.txt     --detected_list=VU_test_data/08/output/OPT_PASPNG.csv     --data_dir=VU_test_data/08/     --staining=OPT_PAS     --output_dir=/l/vision/v5/yiju/glomeruli_detection/VU_test_data/08/output     --output_file_ext=PNG     --conf_threshold=0.9     --overlap_threshold=0.35
python merge_overlapped_glomus.py     --target_list=VU_test_data/09/02_PAS/opt_pas_test_list.txt     --detected_list=VU_test_data/09/output/OPT_PASPNG.csv     --data_dir=VU_test_data/09/     --staining=OPT_PAS     --output_dir=/l/vision/v5/yiju/glomeruli_detection/VU_test_data/09/output     --output_file_ext=PNG     --conf_threshold=0.9     --overlap_threshold=0.35
python merge_overlapped_glomus.py     --target_list=VU_test_data/10/02_PAS/opt_pas_test_list.txt     --detected_list=VU_test_data/10/output/OPT_PASPNG.csv     --data_dir=VU_test_data/10/     --staining=OPT_PAS     --output_dir=/l/vision/v5/yiju/glomeruli_detection/VU_test_data/10/output     --output_file_ext=PNG     --conf_threshold=0.9     --overlap_threshold=0.35
python merge_overlapped_glomus.py     --target_list=VU_test_data/12/02_PAS/opt_pas_test_list.txt     --detected_list=VU_test_data/12/output/OPT_PASPNG.csv     --data_dir=VU_test_data/12/     --staining=OPT_PAS     --output_dir=/l/vision/v5/yiju/glomeruli_detection/VU_test_data/12/output     --output_file_ext=PNG     --conf_threshold=0.9     --overlap_threshold=0.35
python merge_overlapped_glomus.py     --target_list=VU_test_data/13/02_PAS/opt_pas_test_list.txt     --detected_list=VU_test_data/13/output/OPT_PASPNG.csv     --data_dir=VU_test_data/13/     --staining=OPT_PAS     --output_dir=/l/vision/v5/yiju/glomeruli_detection/VU_test_data/13/output     --output_file_ext=PNG     --conf_threshold=0.9     --overlap_threshold=0.35
python merge_overlapped_glomus.py     --target_list=VU_test_data/14/02_PAS/opt_pas_test_list.txt     --detected_list=VU_test_data/14/output/OPT_PASPNG.csv     --data_dir=VU_test_data/14/     --staining=OPT_PAS     --output_dir=/l/vision/v5/yiju/glomeruli_detection/VU_test_data/14/output     --output_file_ext=PNG     --conf_threshold=0.9     --overlap_threshold=0.35
python merge_overlapped_glomus.py     --target_list=VU_test_data/16/02_PAS/opt_pas_test_list.txt     --detected_list=VU_test_data/16/output/OPT_PASPNG.csv     --data_dir=VU_test_data/16/     --staining=OPT_PAS     --output_dir=/l/vision/v5/yiju/glomeruli_detection/VU_test_data/16/output     --output_file_ext=PNG     --conf_threshold=0.9     --overlap_threshold=0.35
python merge_overlapped_glomus.py     --target_list=VU_test_data/52/02_PAS/opt_pas_test_list.txt     --detected_list=VU_test_data/52/output/OPT_PASPNG.csv     --data_dir=VU_test_data/52/     --staining=OPT_PAS     --output_dir=/l/vision/v5/yiju/glomeruli_detection/VU_test_data/52/output     --output_file_ext=PNG     --conf_threshold=0.9     --overlap_threshold=0.35

python -u eval_recall_precision_test.py     --staining=OPT_PAS     --data_dir=VU_test_data/05/     --target_list=VU_test_data/05/02_PAS/opt_pas_test_list.txt     --merged_list=VU_test_data/05/output/OPT_PAS_GlomusMergedList_PNG.csv     --output_dir=/l/vision/v5/yiju/glomeruli_detection/VU_test_data/05/output     --iou_threshold=0.5
python -u eval_recall_precision_test.py     --staining=OPT_PAS     --data_dir=VU_test_data/06/     --target_list=VU_test_data/06/02_PAS/opt_pas_test_list.txt     --merged_list=VU_test_data/06/output/OPT_PAS_GlomusMergedList_PNG.csv     --output_dir=/l/vision/v5/yiju/glomeruli_detection/VU_test_data/06/output     --iou_threshold=0.5
python -u eval_recall_precision_test.py     --staining=OPT_PAS     --data_dir=VU_test_data/07/     --target_list=VU_test_data/07/02_PAS/opt_pas_test_list.txt     --merged_list=VU_test_data/07/output/OPT_PAS_GlomusMergedList_PNG.csv     --output_dir=/l/vision/v5/yiju/glomeruli_detection/VU_test_data/07/output     --iou_threshold=0.5
python -u eval_recall_precision_test.py     --staining=OPT_PAS     --data_dir=VU_test_data/08/     --target_list=VU_test_data/08/02_PAS/opt_pas_test_list.txt     --merged_list=VU_test_data/08/output/OPT_PAS_GlomusMergedList_PNG.csv     --output_dir=/l/vision/v5/yiju/glomeruli_detection/VU_test_data/08/output     --iou_threshold=0.5
python -u eval_recall_precision_test.py     --staining=OPT_PAS     --data_dir=VU_test_data/09/     --target_list=VU_test_data/09/02_PAS/opt_pas_test_list.txt     --merged_list=VU_test_data/09/output/OPT_PAS_GlomusMergedList_PNG.csv     --output_dir=/l/vision/v5/yiju/glomeruli_detection/VU_test_data/09/output     --iou_threshold=0.5
python -u eval_recall_precision_test.py     --staining=OPT_PAS     --data_dir=VU_test_data/10/     --target_list=VU_test_data/10/02_PAS/opt_pas_test_list.txt     --merged_list=VU_test_data/10/output/OPT_PAS_GlomusMergedList_PNG.csv     --output_dir=/l/vision/v5/yiju/glomeruli_detection/VU_test_data/10/output     --iou_threshold=0.5
python -u eval_recall_precision_test.py     --staining=OPT_PAS     --data_dir=VU_test_data/12/     --target_list=VU_test_data/12/02_PAS/opt_pas_test_list.txt     --merged_list=VU_test_data/12/output/OPT_PAS_GlomusMergedList_PNG.csv     --output_dir=/l/vision/v5/yiju/glomeruli_detection/VU_test_data/12/output     --iou_threshold=0.5
python -u eval_recall_precision_test.py     --staining=OPT_PAS     --data_dir=VU_test_data/13/     --target_list=VU_test_data/13/02_PAS/opt_pas_test_list.txt     --merged_list=VU_test_data/13/output/OPT_PAS_GlomusMergedList_PNG.csv     --output_dir=/l/vision/v5/yiju/glomeruli_detection/VU_test_data/13/output     --iou_threshold=0.5
python -u eval_recall_precision_test.py     --staining=OPT_PAS     --data_dir=VU_test_data/14/     --target_list=VU_test_data/14/02_PAS/opt_pas_test_list.txt     --merged_list=VU_test_data/14/output/OPT_PAS_GlomusMergedList_PNG.csv     --output_dir=/l/vision/v5/yiju/glomeruli_detection/VU_test_data/14/output     --iou_threshold=0.5
python -u eval_recall_precision_test.py     --staining=OPT_PAS     --data_dir=VU_test_data/16/     --target_list=VU_test_data/16/02_PAS/opt_pas_test_list.txt     --merged_list=VU_test_data/16/output/OPT_PAS_GlomusMergedList_PNG.csv     --output_dir=/l/vision/v5/yiju/glomeruli_detection/VU_test_data/16/output     --iou_threshold=0.5
python -u eval_recall_precision_test.py     --staining=OPT_PAS     --data_dir=VU_test_data/52/     --target_list=VU_test_data/52/02_PAS/opt_pas_test_list.txt     --merged_list=VU_test_data/52/output/OPT_PAS_GlomusMergedList_PNG.csv     --output_dir=/l/vision/v5/yiju/glomeruli_detection/VU_test_data/52/output     --iou_threshold=0.5

python detect_glomus_test.py     --target_list=VU_test_data/FF03/02_PAS/opt_pas_test_list.txt     --data_dir=VU_test_data/FF03/     --staining=OPT_PAS     --output_dir=/l/vision/v5/yiju/glomeruli_detection/VU_test_data/FF03/output    --output_file_ext=PNG     --model=model/pas_train1/     --window_size=1000     --overlap_ratio=0.5     --conf_threshold=0.2
python detect_glomus_test.py     --target_list=VU_test_data/FF05/02_PAS/opt_pas_test_list.txt     --data_dir=VU_test_data/FF05/     --staining=OPT_PAS     --output_dir=/l/vision/v5/yiju/glomeruli_detection/VU_test_data/FF05/output    --output_file_ext=PNG     --model=model/pas_train1/     --window_size=1000     --overlap_ratio=0.5     --conf_threshold=0.2
python detect_glomus_test.py     --target_list=VU_test_data/FF06/02_PAS/opt_pas_test_list.txt     --data_dir=VU_test_data/FF06/     --staining=OPT_PAS     --output_dir=/l/vision/v5/yiju/glomeruli_detection/VU_test_data/FF06/output    --output_file_ext=PNG     --model=model/pas_train1/     --window_size=1000     --overlap_ratio=0.5     --conf_threshold=0.2
python detect_glomus_test.py     --target_list=VU_test_data/FF09/02_PAS/opt_pas_test_list.txt     --data_dir=VU_test_data/FF09/     --staining=OPT_PAS     --output_dir=/l/vision/v5/yiju/glomeruli_detection/VU_test_data/FF09/output    --output_file_ext=PNG     --model=model/pas_train1/     --window_size=1000     --overlap_ratio=0.5     --conf_threshold=0.2
python detect_glomus_test.py     --target_list=VU_test_data/FF10/02_PAS/opt_pas_test_list.txt     --data_dir=VU_test_data/FF10/     --staining=OPT_PAS     --output_dir=/l/vision/v5/yiju/glomeruli_detection/VU_test_data/FF10/output    --output_file_ext=PNG     --model=model/pas_train1/     --window_size=1000     --overlap_ratio=0.5     --conf_threshold=0.2
python detect_glomus_test.py     --target_list=VU_test_data/FF11/02_PAS/opt_pas_test_list.txt     --data_dir=VU_test_data/FF11/     --staining=OPT_PAS     --output_dir=/l/vision/v5/yiju/glomeruli_detection/VU_test_data/FF11/output    --output_file_ext=PNG     --model=model/pas_train1/     --window_size=1000     --overlap_ratio=0.5     --conf_threshold=0.2
python detect_glomus_test.py     --target_list=VU_test_data/FF13/02_PAS/opt_pas_test_list.txt     --data_dir=VU_test_data/FF13/     --staining=OPT_PAS     --output_dir=/l/vision/v5/yiju/glomeruli_detection/VU_test_data/FF13/output    --output_file_ext=PNG     --model=model/pas_train1/     --window_size=1000     --overlap_ratio=0.5     --conf_threshold=0.2
python detect_glomus_test.py     --target_list=VU_test_data/FF14/02_PAS/opt_pas_test_list.txt     --data_dir=VU_test_data/FF14/     --staining=OPT_PAS     --output_dir=/l/vision/v5/yiju/glomeruli_detection/VU_test_data/FF14/output    --output_file_ext=PNG     --model=model/pas_train1/     --window_size=1000     --overlap_ratio=0.5     --conf_threshold=0.2
python detect_glomus_test.py     --target_list=VU_test_data/FF16/02_PAS/opt_pas_test_list.txt     --data_dir=VU_test_data/FF16/     --staining=OPT_PAS     --output_dir=/l/vision/v5/yiju/glomeruli_detection/VU_test_data/FF16/output    --output_file_ext=PNG     --model=model/pas_train1/     --window_size=1000     --overlap_ratio=0.5     --conf_threshold=0.2

python merge_overlapped_glomus.py     --target_list=VU_test_data/FF03/02_PAS/opt_pas_test_list.txt     --detected_list=VU_test_data/FF03/output/OPT_PASPNG.csv     --data_dir=VU_test_data/FF03/     --staining=OPT_PAS     --output_dir=/l/vision/v5/yiju/glomeruli_detection/VU_test_data/FF03/output     --output_file_ext=PNG     --conf_threshold=0.9     --overlap_threshold=0.35
python merge_overlapped_glomus.py     --target_list=VU_test_data/FF05/02_PAS/opt_pas_test_list.txt     --detected_list=VU_test_data/FF05/output/OPT_PASPNG.csv     --data_dir=VU_test_data/FF05/     --staining=OPT_PAS     --output_dir=/l/vision/v5/yiju/glomeruli_detection/VU_test_data/FF05/output     --output_file_ext=PNG     --conf_threshold=0.9     --overlap_threshold=0.35
python merge_overlapped_glomus.py     --target_list=VU_test_data/FF06/02_PAS/opt_pas_test_list.txt     --detected_list=VU_test_data/FF06/output/OPT_PASPNG.csv     --data_dir=VU_test_data/FF06/     --staining=OPT_PAS     --output_dir=/l/vision/v5/yiju/glomeruli_detection/VU_test_data/FF06/output     --output_file_ext=PNG     --conf_threshold=0.9     --overlap_threshold=0.35
python merge_overlapped_glomus.py     --target_list=VU_test_data/FF09/02_PAS/opt_pas_test_list.txt     --detected_list=VU_test_data/FF09/output/OPT_PASPNG.csv     --data_dir=VU_test_data/FF09/     --staining=OPT_PAS     --output_dir=/l/vision/v5/yiju/glomeruli_detection/VU_test_data/FF09/output     --output_file_ext=PNG     --conf_threshold=0.9     --overlap_threshold=0.35
python merge_overlapped_glomus.py     --target_list=VU_test_data/FF10/02_PAS/opt_pas_test_list.txt     --detected_list=VU_test_data/FF10/output/OPT_PASPNG.csv     --data_dir=VU_test_data/FF10/     --staining=OPT_PAS     --output_dir=/l/vision/v5/yiju/glomeruli_detection/VU_test_data/FF10/output     --output_file_ext=PNG     --conf_threshold=0.9     --overlap_threshold=0.35
python merge_overlapped_glomus.py     --target_list=VU_test_data/FF11/02_PAS/opt_pas_test_list.txt     --detected_list=VU_test_data/FF11/output/OPT_PASPNG.csv     --data_dir=VU_test_data/FF11/     --staining=OPT_PAS     --output_dir=/l/vision/v5/yiju/glomeruli_detection/VU_test_data/FF11/output     --output_file_ext=PNG     --conf_threshold=0.9     --overlap_threshold=0.35
python merge_overlapped_glomus.py     --target_list=VU_test_data/FF13/02_PAS/opt_pas_test_list.txt     --detected_list=VU_test_data/FF13/output/OPT_PASPNG.csv     --data_dir=VU_test_data/FF13/     --staining=OPT_PAS     --output_dir=/l/vision/v5/yiju/glomeruli_detection/VU_test_data/FF13/output     --output_file_ext=PNG     --conf_threshold=0.9     --overlap_threshold=0.35
python merge_overlapped_glomus.py     --target_list=VU_test_data/FF14/02_PAS/opt_pas_test_list.txt     --detected_list=VU_test_data/FF14/output/OPT_PASPNG.csv     --data_dir=VU_test_data/FF14/     --staining=OPT_PAS     --output_dir=/l/vision/v5/yiju/glomeruli_detection/VU_test_data/FF14/output     --output_file_ext=PNG     --conf_threshold=0.9     --overlap_threshold=0.35
python merge_overlapped_glomus.py     --target_list=VU_test_data/FF16/02_PAS/opt_pas_test_list.txt     --detected_list=VU_test_data/FF16/output/OPT_PASPNG.csv     --data_dir=VU_test_data/FF16/     --staining=OPT_PAS     --output_dir=/l/vision/v5/yiju/glomeruli_detection/VU_test_data/FF16/output     --output_file_ext=PNG     --conf_threshold=0.9     --overlap_threshold=0.35

python -u eval_recall_precision_test.py     --staining=OPT_PAS     --data_dir=VU_test_data/FF03/     --target_list=VU_test_data/FF03/02_PAS/opt_pas_test_list.txt     --merged_list=VU_test_data/FF03/output/OPT_PAS_GlomusMergedList_PNG.csv     --output_dir=/l/vision/v5/yiju/glomeruli_detection/VU_test_data/FF03/output     --iou_threshold=0.5
python -u eval_recall_precision_test.py     --staining=OPT_PAS     --data_dir=VU_test_data/FF05/     --target_list=VU_test_data/FF05/02_PAS/opt_pas_test_list.txt     --merged_list=VU_test_data/FF05/output/OPT_PAS_GlomusMergedList_PNG.csv     --output_dir=/l/vision/v5/yiju/glomeruli_detection/VU_test_data/FF05/output     --iou_threshold=0.5
python -u eval_recall_precision_test.py     --staining=OPT_PAS     --data_dir=VU_test_data/FF06/     --target_list=VU_test_data/FF06/02_PAS/opt_pas_test_list.txt     --merged_list=VU_test_data/FF06/output/OPT_PAS_GlomusMergedList_PNG.csv     --output_dir=/l/vision/v5/yiju/glomeruli_detection/VU_test_data/FF06/output     --iou_threshold=0.5
python -u eval_recall_precision_test.py     --staining=OPT_PAS     --data_dir=VU_test_data/FF09/     --target_list=VU_test_data/FF09/02_PAS/opt_pas_test_list.txt     --merged_list=VU_test_data/FF09/output/OPT_PAS_GlomusMergedList_PNG.csv     --output_dir=/l/vision/v5/yiju/glomeruli_detection/VU_test_data/FF09/output     --iou_threshold=0.5
python -u eval_recall_precision_test.py     --staining=OPT_PAS     --data_dir=VU_test_data/FF10/     --target_list=VU_test_data/FF10/02_PAS/opt_pas_test_list.txt     --merged_list=VU_test_data/FF10/output/OPT_PAS_GlomusMergedList_PNG.csv     --output_dir=/l/vision/v5/yiju/glomeruli_detection/VU_test_data/FF10/output     --iou_threshold=0.5
python -u eval_recall_precision_test.py     --staining=OPT_PAS     --data_dir=VU_test_data/FF11/     --target_list=VU_test_data/FF11/02_PAS/opt_pas_test_list.txt     --merged_list=VU_test_data/FF11/output/OPT_PAS_GlomusMergedList_PNG.csv     --output_dir=/l/vision/v5/yiju/glomeruli_detection/VU_test_data/FF11/output     --iou_threshold=0.5
python -u eval_recall_precision_test.py     --staining=OPT_PAS     --data_dir=VU_test_data/FF13/     --target_list=VU_test_data/FF13/02_PAS/opt_pas_test_list.txt     --merged_list=VU_test_data/FF13/output/OPT_PAS_GlomusMergedList_PNG.csv     --output_dir=/l/vision/v5/yiju/glomeruli_detection/VU_test_data/FF13/output     --iou_threshold=0.5
python -u eval_recall_precision_test.py     --staining=OPT_PAS     --data_dir=VU_test_data/FF14/     --target_list=VU_test_data/FF14/02_PAS/opt_pas_test_list.txt     --merged_list=VU_test_data/FF14/output/OPT_PAS_GlomusMergedList_PNG.csv     --output_dir=/l/vision/v5/yiju/glomeruli_detection/VU_test_data/FF14/output     --iou_threshold=0.5
python -u eval_recall_precision_test.py     --staining=OPT_PAS     --data_dir=VU_test_data/FF16/     --target_list=VU_test_data/FF16/02_PAS/opt_pas_test_list.txt     --merged_list=VU_test_data/FF16/output/OPT_PAS_GlomusMergedList_PNG.csv     --output_dir=/l/vision/v5/yiju/glomeruli_detection/VU_test_data/FF16/output     --iou_threshold=0.5

python image_patch_cropping.py ../visualization/annotations/VAN0005-RK-1-1-AF_preIMS_registered_glomerulus_detections.json X:\VU_test_data\05\output\OPT_PAS_GlomusMergedList_PNG.csv X:\VAN0005-RK-1-1-PAS_registered.ome.tiff 1 1
python image_patch_cropping.py ../visualization/annotations/VAN0005-RK-4-172-AF_preIMS_registered_glomerulus_detections.json X:\VU_test_data\52\output\OPT_PAS_GlomusMergedList_PNG.csv X:\VAN0005-RK-4-172-PAS_registered.ome.tiff 1 1
python image_patch_cropping.py ../visualization/annotations/VAN0006-LK-2-85-AF_preIMS_registered_glomerulus_detections.json X:\VU_test_data\06\output\OPT_PAS_GlomusMergedList_PNG.csv X:\VAN0006-LK-2-85-PAS_registered.ome.tiff 1 1
python image_patch_cropping.py ../visualization/annotations/VAN0007-LK-203-103-AF_preIMS_registered_glomerulus_detections.json X:\VU_test_data\07\output\OPT_PAS_GlomusMergedList_PNG.csv X:\VAN0007-LK-203-103-PAS_registered.ome.tiff 1 1
python image_patch_cropping.py ../visualization/annotations/VAN0008-RK-403-100-AF_preIMS_registered_glomerulus_detections.json X:\VU_test_data\08\output\OPT_PAS_GlomusMergedList_PNG.csv X:\VAN0008-RK-403-100-PAS_registered.ome.tiff 1 1
python image_patch_cropping.py ../visualization/annotations/VAN0009-LK-102-7-AF_preIMS_registered_glomerulus_detections.json X:\VU_test_data\09\output\OPT_PAS_GlomusMergedList_PNG.csv X:\VAN0009-LK-102-7-PAS_registered.ome.tiff 1 1
python image_patch_cropping.py ../visualization/annotations/VAN0010-LK-155-40-AF_preIMS_registered_glomerulus_detections.json X:\VU_test_data\10\output\OPT_PAS_GlomusMergedList_PNG.csv X:\VAN0010-LK-155-40-PAS_registered.ome.tiff 1 1
python image_patch_cropping.py ../visualization/annotations/VAN0012-RK-103-75-AF_preIMS_registered_glomerulus_detections.json X:\VU_test_data\12\output\OPT_PAS_GlomusMergedList_PNG.csv X:\VAN0012-RK-103-75-PAS_registered.ome.tiff 1 1
python image_patch_cropping.py ../visualization/annotations/VAN0013-LK-202-96-AF_preIMS_registered_glomerulus_detections.json X:\VU_test_data\13\output\OPT_PAS_GlomusMergedList_PNG.csv X:\VAN0013-LK-202-96-PAS_registered.ome.tiff 1 1
python image_patch_cropping.py ../visualization/annotations/VAN0014-LK-203-108-AF_preIMS_registered_glomerulus_detections.json X:\VU_test_data\14\output\OPT_PAS_GlomusMergedList_PNG.csv X:\VAN0014-LK-203-108-PAS_registered.ome.tiff 1 1
python image_patch_cropping.py ../visualization/annotations/VAN0016-LK-202-89-AF_preIMS_registered_glomerulus_detections.json X:\VU_test_data\16\output\OPT_PAS_GlomusMergedList_PNG.csv X:\VAN0016-LK-202-89-PAS_registered.ome.tiff 1 1

python image_patch_cropping.py ../visualization/annotations/VAN0003-LK-33-2-PAS_FFPE_glom_annotations.json X:\VU_test_data\FF03\output\OPT_PAS_GlomusMergedList_PNG.csv X:\VAN0003-LK-33-2-PAS_FFPE.ome.tiff 1 1
python image_patch_cropping.py ../visualization/annotations/VAN0005-RK-8-2-PAS_FFPE_glom_annotations.json X:\VU_test_data\FF05\output\OPT_PAS_GlomusMergedList_PNG.csv X:\VAN0005-RK-8-2-PAS_FFPE.ome.tiff 1 1
python image_patch_cropping.py ../visualization/annotations/VAN0006-LK-7-2-PAS_FFPE_glom_annotations.json X:\VU_test_data\FF06\output\OPT_PAS_GlomusMergedList_PNG.csv X:\VAN0006-LK-7-2-PAS_FFPE.ome.tiff 1 1
python image_patch_cropping.py ../visualization/annotations/VAN0009-LK-106-2-PAS_FFPE_glom_annotations.json X:\VU_test_data\FF09\output\OPT_PAS_GlomusMergedList_PNG.csv X:\VAN0009-LK-106-2-PAS_FFPE.ome.tiff 1 1
python image_patch_cropping.py ../visualization/annotations/VAN0010-LK-160-2-PAS_FFPE_glom_annotations.json X:\VU_test_data\FF10\output\OPT_PAS_GlomusMergedList_PNG.csv X:\VAN0010-LK-160-2-PAS_FFPE.ome.tiff 1 1
python image_patch_cropping.py ../visualization/annotations/VAN0011-RK-33-2-PAS_FFPE_glom_annotations.json X:\VU_test_data\FF11\output\OPT_PAS_GlomusMergedList_PNG.csv X:\VAN0011-RK-33-2-PAS_FFPE.ome.tiff 1 1
python image_patch_cropping.py ../visualization/annotations/VAN0013-LK-206-2-PAS_FFPE_glom_annotations.json X:\VU_test_data\FF13\output\OPT_PAS_GlomusMergedList_PNG.csv X:\VAN0013-LK-206-2-PAS_FFPE.ome.tiff 1 1
python image_patch_cropping.py ../visualization/annotations/VAN0014-LK-207-2-PAS_FFPE_glom_annotations.json X:\VU_test_data\FF14\output\OPT_PAS_GlomusMergedList_PNG.csv X:\VAN0014-LK-207-2-PAS_FFPE.ome.tiff 1 1
python image_patch_cropping.py ../visualization/annotations/VAN0016-LK-208-2-PAS_FFPE_glom_annotations.json X:\VU_test_data\FF16\output\OPT_PAS_GlomusMergedList_PNG.csv X:\VAN0016-LK-208-2-PAS_FFPE.ome.tiff 1 1
