#!/usr/bin/env bash

python detect_glomus_test.py     --target_list=VU_test_data/05/02_PAS/opt_pas_test_list.txt     --data_dir=VU_test_data/05/     --staining=OPT_PAS     --output_dir=/l/vision/v5/yiju/glomeruli_detection/VU_test_data/05/output    --output_file_ext=PNG     --model=model/pas_train1/     --window_size=1000     --overlap_ratio=0.5     --conf_threshold=0.2
python detect_glomus_test.py     --target_list=VU_test_data/06/02_PAS/opt_pas_test_list.txt     --data_dir=VU_test_data/06/     --staining=OPT_PAS     --output_dir=/l/vision/v5/yiju/glomeruli_detection/VU_test_data/06/output    --output_file_ext=PNG     --model=model/pas_train1/     --window_size=1000     --overlap_ratio=0.5     --conf_threshold=0.2
python detect_glomus_test.py     --target_list=VU_test_data/07/02_PAS/opt_pas_test_list.txt     --data_dir=VU_test_data/07/     --staining=OPT_PAS     --output_dir=/l/vision/v5/yiju/glomeruli_detection/VU_test_data/07/output    --output_file_ext=PNG     --model=model/pas_train1/     --window_size=1000     --overlap_ratio=0.5     --conf_threshold=0.2
python detect_glomus_test.py     --target_list=VU_test_data/08/02_PAS/opt_pas_test_list.txt     --data_dir=VU_test_data/08/     --staining=OPT_PAS     --output_dir=/l/vision/v5/yiju/glomeruli_detection/VU_test_data/08/output    --output_file_ext=PNG     --model=model/pas_train1/     --window_size=1000     --overlap_ratio=0.5     --conf_threshold=0.2
python detect_glomus_test.py     --target_list=VU_test_data/09/02_PAS/opt_pas_test_list.txt     --data_dir=VU_test_data/09/     --staining=OPT_PAS     --output_dir=/l/vision/v5/yiju/glomeruli_detection/VU_test_data/09/output    --output_file_ext=PNG     --model=model/pas_train1/     --window_size=1000     --overlap_ratio=0.5     --conf_threshold=0.2
python detect_glomus_test.py     --target_list=VU_test_data/10/02_PAS/opt_pas_test_list.txt     --data_dir=VU_test_data/10/     --staining=OPT_PAS     --output_dir=/l/vision/v5/yiju/glomeruli_detection/VU_test_data/10/output    --output_file_ext=PNG     --model=model/pas_train1/     --window_size=1000     --overlap_ratio=0.5     --conf_threshold=0.2
python detect_glomus_test.py     --target_list=VU_test_data/12/02_PAS/opt_pas_test_list.txt     --data_dir=VU_test_data/12/     --staining=OPT_PAS     --output_dir=/l/vision/v5/yiju/glomeruli_detection/VU_test_data/12/output    --output_file_ext=PNG     --model=model/pas_train1/     --window_size=1000     --overlap_ratio=0.5     --conf_threshold=0.2
python detect_glomus_test.py     --target_list=VU_test_data/13/02_PAS/opt_pas_test_list.txt     --data_dir=VU_test_data/13/     --staining=OPT_PAS     --output_dir=/l/vision/v5/yiju/glomeruli_detection/VU_test_data/13/output    --output_file_ext=PNG     --model=model/pas_train1/     --window_size=1000     --overlap_ratio=0.5     --conf_threshold=0.2
python detect_glomus_test.py     --target_list=VU_test_data/14/02_PAS/opt_pas_test_list.txt     --data_dir=VU_test_data/14/     --staining=OPT_PAS     --output_dir=/l/vision/v5/yiju/glomeruli_detection/VU_test_data/14/output    --output_file_ext=PNG     --model=model/pas_train1/     --window_size=1000     --overlap_ratio=0.5     --conf_threshold=0.2
python detect_glomus_test.py     --target_list=VU_test_data/16/02_PAS/opt_pas_test_list.txt     --data_dir=VU_test_data/16/     --staining=OPT_PAS     --output_dir=/l/vision/v5/yiju/glomeruli_detection/VU_test_data/16/output    --output_file_ext=PNG     --model=model/pas_train1/     --window_size=1000     --overlap_ratio=0.5     --conf_threshold=0.2
python detect_glomus_test.py     --target_list=VU_test_data/52/02_PAS/opt_pas_test_list.txt     --data_dir=VU_test_data/52/     --staining=OPT_PAS     --output_dir=/l/vision/v5/yiju/glomeruli_detection/VU_test_data/52/output    --output_file_ext=PNG     --model=model/pas_train1/     --window_size=1000     --overlap_ratio=0.5     --conf_threshold=0.2

python merge_overlapped_glomus.py     --target_list=VU_test_data/05/02_PAS/opt_pas_test_list.txt     --detected_list=VU_test_data/05/output/OPT_PASPNG.csv     --data_dir=VU_test_data/05/     --staining=OPT_PAS     --output_dir=/l/vision/v5/yiju/glomeruli_detection/VU_test_data/05/output     --output_file_ext=PNG     --conf_threshold=0.9     --overlap_threshold=0.35
python merge_overlapped_glomus.py     --target_list=VU_test_data/06/02_PAS/opt_pas_test_list.txt     --detected_list=VU_test_data/06/output/OPT_PASPNG.csv     --data_dir=VU_test_data/06/     --staining=OPT_PAS     --output_dir=/l/vision/v5/yiju/glomeruli_detection/VU_test_data/06/output     --output_file_ext=PNG     --conf_threshold=0.9     --overlap_threshold=0.35
python merge_overlapped_glomus.py     --target_list=VU_test_data/07/02_PAS/opt_pas_test_list.txt     --detected_list=VU_test_data/07/output/OPT_PASPNG.csv     --data_dir=VU_test_data/07/     --staining=OPT_PAS     --output_dir=/l/vision/v5/yiju/glomeruli_detection/VU_test_data/07/output     --output_file_ext=PNG     --conf_threshold=0.9     --overlap_threshold=0.35
python merge_overlapped_glomus.py     --target_list=VU_test_data/08/02_PAS/opt_pas_test_list.txt     --detected_list=VU_test_data/08/output/OPT_PASPNG.csv     --data_dir=VU_test_data/08/     --staining=OPT_PAS     --output_dir=/l/vision/v5/yiju/glomeruli_detection/VU_test_data/08/output     --output_file_ext=PNG     --conf_threshold=0.9     --overlap_threshold=0.35
python merge_overlapped_glomus.py     --target_list=VU_test_data/09/02_PAS/opt_pas_test_list.txt     --detected_list=VU_test_data/09/output/OPT_PASPNG.csv     --data_dir=VU_test_data/09/     --staining=OPT_PAS     --output_dir=/l/vision/v5/yiju/glomeruli_detection/VU_test_data/09/output     --output_file_ext=PNG     --conf_threshold=0.9     --overlap_threshold=0.35
python merge_overlapped_glomus.py     --target_list=VU_test_data/10/02_PAS/opt_pas_test_list.txt     --detected_list=VU_test_data/10/output/OPT_PASPNG.csv     --data_dir=VU_test_data/10/     --staining=OPT_PAS     --output_dir=/l/vision/v5/yiju/glomeruli_detection/VU_test_data/10/output     --output_file_ext=PNG     --conf_threshold=0.9     --overlap_threshold=0.35
python merge_overlapped_glomus.py     --target_list=VU_test_data/12/02_PAS/opt_pas_test_list.txt     --detected_list=VU_test_data/12/output/OPT_PASPNG.csv     --data_dir=VU_test_data/12/     --staining=OPT_PAS     --output_dir=/l/vision/v5/yiju/glomeruli_detection/VU_test_data/12/output     --output_file_ext=PNG     --conf_threshold=0.9     --overlap_threshold=0.35
python merge_overlapped_glomus.py     --target_list=VU_test_data/13/02_PAS/opt_pas_test_list.txt     --detected_list=VU_test_data/13/output/OPT_PASPNG.csv     --data_dir=VU_test_data/13/     --staining=OPT_PAS     --output_dir=/l/vision/v5/yiju/glomeruli_detection/VU_test_data/13/output     --output_file_ext=PNG     --conf_threshold=0.9     --overlap_threshold=0.35
python merge_overlapped_glomus.py     --target_list=VU_test_data/14/02_PAS/opt_pas_test_list.txt     --detected_list=VU_test_data/14/output/OPT_PASPNG.csv     --data_dir=VU_test_data/14/     --staining=OPT_PAS     --output_dir=/l/vision/v5/yiju/glomeruli_detection/VU_test_data/14/output     --output_file_ext=PNG     --conf_threshold=0.9     --overlap_threshold=0.35
python merge_overlapped_glomus.py     --target_list=VU_test_data/16/02_PAS/opt_pas_test_list.txt     --detected_list=VU_test_data/16/output/OPT_PASPNG.csv     --data_dir=VU_test_data/16/     --staining=OPT_PAS     --output_dir=/l/vision/v5/yiju/glomeruli_detection/VU_test_data/16/output     --output_file_ext=PNG     --conf_threshold=0.9     --overlap_threshold=0.35
python merge_overlapped_glomus.py     --target_list=VU_test_data/52/02_PAS/opt_pas_test_list.txt     --detected_list=VU_test_data/52/output/OPT_PASPNG.csv     --data_dir=VU_test_data/52/     --staining=OPT_PAS     --output_dir=/l/vision/v5/yiju/glomeruli_detection/VU_test_data/52/output     --output_file_ext=PNG     --conf_threshold=0.9     --overlap_threshold=0.35

python -u eval_recall_precision_test.py     --staining=OPT_PAS     --data_dir=VU_test_data/05/     --target_list=VU_test_data/05/02_PAS/opt_pas_test_list.txt     --merged_list=VU_test_data/05/output/OPT_PAS_GlomusMergedList_PNG.csv     --output_dir=/l/vision/v5/yiju/glomeruli_detection/VU_test_data/05/output     --iou_threshold=0.5
python -u eval_recall_precision_test.py     --staining=OPT_PAS     --data_dir=VU_test_data/06/     --target_list=VU_test_data/06/02_PAS/opt_pas_test_list.txt     --merged_list=VU_test_data/06/output/OPT_PAS_GlomusMergedList_PNG.csv     --output_dir=/l/vision/v5/yiju/glomeruli_detection/VU_test_data/06/output     --iou_threshold=0.5
python -u eval_recall_precision_test.py     --staining=OPT_PAS     --data_dir=VU_test_data/07/     --target_list=VU_test_data/07/02_PAS/opt_pas_test_list.txt     --merged_list=VU_test_data/07/output/OPT_PAS_GlomusMergedList_PNG.csv     --output_dir=/l/vision/v5/yiju/glomeruli_detection/VU_test_data/07/output     --iou_threshold=0.5
python -u eval_recall_precision_test.py     --staining=OPT_PAS     --data_dir=VU_test_data/08/     --target_list=VU_test_data/08/02_PAS/opt_pas_test_list.txt     --merged_list=VU_test_data/08/output/OPT_PAS_GlomusMergedList_PNG.csv     --output_dir=/l/vision/v5/yiju/glomeruli_detection/VU_test_data/08/output     --iou_threshold=0.5
python -u eval_recall_precision_test.py     --staining=OPT_PAS     --data_dir=VU_test_data/09/     --target_list=VU_test_data/09/02_PAS/opt_pas_test_list.txt     --merged_list=VU_test_data/09/output/OPT_PAS_GlomusMergedList_PNG.csv     --output_dir=/l/vision/v5/yiju/glomeruli_detection/VU_test_data/09/output     --iou_threshold=0.5
python -u eval_recall_precision_test.py     --staining=OPT_PAS     --data_dir=VU_test_data/10/     --target_list=VU_test_data/10/02_PAS/opt_pas_test_list.txt     --merged_list=VU_test_data/10/output/OPT_PAS_GlomusMergedList_PNG.csv     --output_dir=/l/vision/v5/yiju/glomeruli_detection/VU_test_data/10/output     --iou_threshold=0.5
python -u eval_recall_precision_test.py     --staining=OPT_PAS     --data_dir=VU_test_data/12/     --target_list=VU_test_data/12/02_PAS/opt_pas_test_list.txt     --merged_list=VU_test_data/12/output/OPT_PAS_GlomusMergedList_PNG.csv     --output_dir=/l/vision/v5/yiju/glomeruli_detection/VU_test_data/12/output     --iou_threshold=0.5
python -u eval_recall_precision_test.py     --staining=OPT_PAS     --data_dir=VU_test_data/13/     --target_list=VU_test_data/13/02_PAS/opt_pas_test_list.txt     --merged_list=VU_test_data/13/output/OPT_PAS_GlomusMergedList_PNG.csv     --output_dir=/l/vision/v5/yiju/glomeruli_detection/VU_test_data/13/output     --iou_threshold=0.5
python -u eval_recall_precision_test.py     --staining=OPT_PAS     --data_dir=VU_test_data/14/     --target_list=VU_test_data/14/02_PAS/opt_pas_test_list.txt     --merged_list=VU_test_data/14/output/OPT_PAS_GlomusMergedList_PNG.csv     --output_dir=/l/vision/v5/yiju/glomeruli_detection/VU_test_data/14/output     --iou_threshold=0.5
python -u eval_recall_precision_test.py     --staining=OPT_PAS     --data_dir=VU_test_data/16/     --target_list=VU_test_data/16/02_PAS/opt_pas_test_list.txt     --merged_list=VU_test_data/16/output/OPT_PAS_GlomusMergedList_PNG.csv     --output_dir=/l/vision/v5/yiju/glomeruli_detection/VU_test_data/16/output     --iou_threshold=0.5
python -u eval_recall_precision_test.py     --staining=OPT_PAS     --data_dir=VU_test_data/52/     --target_list=VU_test_data/52/02_PAS/opt_pas_test_list.txt     --merged_list=VU_test_data/52/output/OPT_PAS_GlomusMergedList_PNG.csv     --output_dir=/l/vision/v5/yiju/glomeruli_detection/VU_test_data/52/output     --iou_threshold=0.5
